export default {
	ADD_TODO: 'ADD_TODO',
	TOGGLE_TODO:'TOGGLE_TODO',
	TOGGLE_EDIT: 'TOGGLE_EDIT',
	EDIT: 'EDIT',
	DELETE: 'DELETE',
	EDIT_DESCRIPTION: 'EDIT_DESCRIPTION',
	REPLACE_ALL : 'REPLACE_ALL',
	GET_ALL : 'GET_ALL',
};